# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc7604b64919e00553c5f162ec96d3fe9a75d7cebbd2e329c86047e4b013f1e9be50a51882c9fec03dc5ccb9eee57a96a67b4b8651d7a0b00257a6a1d889fe8b

test:
  secret_key_base: 5a8b95d1e1a876650c3917167ff2c9ea529148d4d7e7939170f03e76c2472e5dc5904bb4447569d184be391ec0d9b1e29d09d9a890b5a538f1e9497e9e2ddf1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
